#!/bin/bash

PROJECT=$1

# File Extensions
_ASM_EXT=asm
_MD_ROM_EXT=bin
_FLAGS="-no-opt -nosym -Fbin"

echo "Building ${PROJECT}"

cd ${PROJECT}

if [[ $? != 0 ]]; then
    echo "Unable to find project: ${PROJECT}"
    exit 1
fi
    
rm -rfv *.${_MD_ROM_EXT}

echo
vasmm68k-mot ${_FLAGS} \
    -o ${PROJECT}.${_MD_ROM_EXT} \
    ${PROJECT}.${_ASM_EXT}

BUILD_RESULT=$?

echo

if [[ ${BUILD_RESULT} == 0 ]]; then

    echo
    echo "Build Succeeded! :D"
    echo

    # Padd File
    #echo "Padding rom to 1MB..."
    #echo `pwd`
    #../tools/PadTo1M  ${PROJECT}.${_MD_ROM_EXT}

    # Fix Checksum
    echo Fixing Checksum...
    ../tools/FixChecksum.py  ${PROJECT}.${_MD_ROM_EXT}

    echo
    echo "Running 'file and ls -la' on " ${PROJECT}.${_MD_ROM_EXT}
    ls -la ${PROJECT}.${_MD_ROM_EXT}
    file ${PROJECT}.${_MD_ROM_EXT}
    echo

    #echo Running BlastEm
    ~/software/blastem/blastem -d ${PROJECT}.${_MD_ROM_EXT}

    exit 0
else
    echo "Build Failed :("
    exit 1
fi
